### ISSUE TITLE
Installing Modpacks using this wrapper

### ISSUE THREAD

**Issue by sidambhire** [ZekerZhayard/ForgeWrapper#1]
Hello @ZekerZhayard ,
I tried to install a modpack: [Enigmatica 4](https://www.curseforge.com/minecraft/modpacks/enigmatica4) using your wrapper. I couldn't install it in correct directory. The wrapper creates a new folder for the instance (as you have stated in your README.md) but does not install it in the modpack instance downloaded by MultiMC (I used import from zip). I copied all mods from the folder Enigmatica 4 instance to the newly created forge instance. It was working.

Can this feature be added to your wrapper? It'll help a lot. Thanks!

**Comment by ZekerZhayard** [comment]
Added.
Use `java -jar ForgeWrapper-1.2.0.jar --cursepack=<Enigmatica4.zip>` to install the modpack.
See README.md for more information.

**Comment by sidambhire** [comment]
Thanks. I checked the newly installed instance. It was working. Only thing different from the previous one was that I couldn't see installed mods under the mods tab. Maybe because they were installed in `cursemods` folder.

Marking this as closed.
