### ISSUE TITLE
Java properties not working?

### ISSUE THREAD

**Issue by eDexiam** [ZekerZhayard/ForgeWrapper#2]
Hi there, I can't get Java property to work, I'm not exactly sure why but here is the error I am getting.
![image](https://user-images.githubusercontent.com/29255472/88440930-cbf6c580-ce0f-11ea-8de7-7f6929b2ec9d.png)

I am using the Java properties according to the readme.

**Comment by ZekerZhayard** [comment]
Java properties are used in Minecraft Launcher, not in ForgeWrapper converter.

**Comment by eDexiam** [comment]
So, how can I set it up then?

**Comment by ZekerZhayard** [comment]
Which launcher are you using?

**Comment by eDexiam** [comment]
I'm using this launcher 
https://github.com/dscalzi/HeliosLauncher

**Comment by ZekerZhayard** [comment]
I still can’t understand how this launcher works after taking a few hours.
can you tell me some more information?

**Comment by eDexiam** [comment]
Sure, the launcher works on a modpack basis, the modpack is downloaded from a server, the problem with it is that it downloads the forge jar client for that server as well which is not allowed because of minecraft's EULA, so I would like to try to use your wrapper to install forge automatically on clients

**Comment by jamierocks** [comment]
Just to interject a bit here - the error message does say how you should be invoking ForgeWrapper.

**Comment by ZekerZhayard** [comment]
oh, ForgeWrapper couldn't do this. 
the role of ForgeWrapper is to install Forge 1.13+ after clicking "launch game" button in the launcher and before the game actually 
being launched.

**Comment by eDexiam** [comment]
That's what I'm trying to implement using forge wrapper

**Comment by Pyker** [comment]
I think you should be adding ForgeWrapper in the classpath, and then call the actual right class (and not the entrypoint of the JAR, which is the outdated/unused Converter class), but I might be wrong about this.
