### ISSUE TITLE
Java Classloading Modification & Sporadic Startup Crashing

### ISSUE THREAD

**Issue by SalmonSays** [ZekerZhayard/ForgeWrapper#5]
Note: I've spent the last few nights troubleshooting this issue remotely as I can't personally recreate the conditions, so bear with me because the details are slightly *weird*.

ForgeWrapper is the commonality between MultiMC and Technic, platforms where startup crashes occur only for *some* players *some* (re: 90-ish%?) of the time on a modded Forge 36.0.1 MC 1.16.5 instance. After spending days drilling down the source of the crashes with the Forge team Discord, we suspect it's down to the way Java Classloading is handled right off the hop through this wrapper? We've eliminated as many variables as we can, but the smoking gun is that a freshly installed and otherwise identical Forge instance installed over top of Minecraft's official launcher works fine while MultiMC and Technic modpacks fail reliably but not predictably with the same sets of mods/configs. Further complicating this, about 50% of users (from a sample set of 7 or 8) have *no* problems at all, myself included. We've been racking our brains trying to find the variable at play here between working/not working users- OS, CPU/GPU configuration, Java install, etc but nothing is clearly at fault!

I'm hopeful this is the right place to seek help/escalate the issue, and for what it's worth we're willing to help provide as much debug/test information as needed to help narrow it down into a corner.

![unknown](https://user-images.githubusercontent.com/11697389/105747003-ce90bf80-5f05-11eb-93c1-ddb666f71a11.png)

At face value the crash appears to manifest this way, with lots of "encountered an error during the common_setup event phase" being spat out from _different mods every launch_ with the occasional full window crash and no GUI output. We've pulled mods a few at a time ad nauseum, gotten rid of all coremods/mixins/anything invasive, and tested identical file structures between working/not working machines reliably. I've never seen an issue quite like this before and am overwhelmingly stumped, but not deterred from trying to be helpful in making a fix happen 😅

**Comment by ZekerZhayard** [comment]
Can you provide debug.log when these exceptions appeared? I'm also interested in this because this never happened to me and  does not seem to have been reported in MultiMC Discord.
